version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx3.conf:/etc/nginx/conf.d/default.conf
            # - ./ssl/oneid.crt:/etc/nginx/ssl/nginx.cert
            # - ./ssl/oneid.key:/etc/nginx/ssl/nginx.key
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
